#!/bin/sh

waitron wm_config border_width 0
waitron wm_config color_focused #1cfa67
waitron wm_config color_unfocused #84d498
waitron wm_config gap_width all 0
waitron wm_config grid_gap_width 0
waitron wm_config cursor_position middle
waitron wm_config groups_nr 9
waitron wm_config enable_resize_hints false
waitron wm_config enable_sloppy_focus true
waitron wm_config sticky_windows false
waitron wm_config enable_borders false
waitron wm_config enable_last_window_focusing true
waitron wm_config apply_settings true
waitron wm_config replay_click_on_focus true
waitron wm_config pointer_actions move resize_side resize_corner
waitron wm_config pointer_modifier super
waitron wm_config click_to_focus any

sxhkd &
lemonbar -p &
i3status --config ~/.config/status-windowchef.conf
compton --config ${HOME}/.config/compton/compton.conf -b
feh --bg-scale ${HOME}/Pics/cybergamebak.jpg &
